#!/usr/bin/env python
# -*- coding: utf-8 -*-

def solution(n, m):
    print("n: " + str(n) + " → " + format(n, "32b").strip())
    print("m: " + str(m) + " → " + format(m, "32b").strip())
    output = (n + 1) ^ (m + 1)
    print("out: " + str(output) + " → " + format(output, "32b").strip())
    return output


def main():
    n = 11
    m = 13
    print(solution(n, m))

if __name__ == "__main__":
    main()

