#!/usr/bin/env bash

python_folder=Python

if [[ -z $1 || $1 == "-r" && -z $2 ]]; then
    echo "Missing filenames"
    exit 1
elif [[ $1 == "-h" ]]; then
    echo -e "Usage: ./setPython NAME\nOptions:\n"\
            "-r NAME → Restore 'NAME.py' and 'test_NAME.py'\n"\
            "-e edit with nvim\n"\
            "-c || -d → Clean\n -m → move to '${python_folder}'"
    exit
elif [[ $1 == "-m" ]]; then
    rm __main__.py
    rm -r __pycache__
    mv ./*.py Python
    exit
elif [[ $1 == "-r" ]]; then
    cp "$python_folder"/"$2".py "$2".py
    cp "$python_folder"/test_"$2".py test_"$2".py
    ln -sfn "$2".py __main__.py
    exit
elif [[ $1 == "-e" ]]; then
    nvim ./*.py
    exit
elif [[ $1 == "-c" || $1 == "-d" ]]; then
    rm -r __pycache__
    rm ./*.py
    exit
elif [[ -e $1.py || -e test_$1.py ]]; then
    echo "A file with the same name already exists."
    exit 1
fi

cp "$python_folder"/template.py "$1".py
cp "$python_folder"/template_test.py test_"$1".py
ln -sfn "$1".py __main__.py
sed -i "s/REPLACE/$1/" test_"$1".py
nvim "$1".py test_"$1".py
